server:
  port: ${SERVER_PORT:8084}
spring:
  application:
    name: notification-service
  profiles:
    default: local
management:
  endpoints:
    web:
      exposure:
        include: health,info
