server:
  port: ${SERVER_PORT:8081}
spring:
  application:
    name: approval-service
  profiles:
    default: local
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
management:
  endpoints:
    web:
      exposure:
        include: health,info
